// src/research/snapshot-tier-catalog.ts
import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Typed reader for the repo-root `snapshot-tiers.json` (wfo-extended-fixture item 4, lab side).
 * That file is GENERATED by control-center's `pnpm sync` from `ecosystem-defaults.yaml` and
 * committed byte-for-byte into every consumer repo — never hand-edited here. This module's job is
 * narrow: read it, validate its schema version, and answer "which tier clears N days of history"
 * so callers can fail fast and NAME the tier instead of discovering `insufficient_history` deep
 * inside `resolveHoldoutBoundary` after an expensive sanity run already ran.
 *
 * Fail-closed by design: a missing file or an unrecognized `schemaVersion` throws immediately —
 * there is no silent fallback, because a stale/absent catalog must never be mistaken for "no tier
 * is deep enough".
 */

const SNAPSHOT_TIERS_SCHEMA_VERSION = 'snapshot-tiers.1';
const MINUTES_PER_DAY = 1440;

export interface SnapshotTierEntry {
  ref: string;
  purpose: string;
  native_1m: boolean;
  primary_symbol: string;
  symbols: number;
  bar_timeframes: string[];
  window: { from: string; to: string };
  window_minutes: number;
  primary_present_minutes: number;
  common_present_minutes: number;
  in_demo_image: boolean;
}

export interface SnapshotTierCatalog {
  schemaVersion: string;
  defaultTier: string;
  minWfoHistoryDays: number;
  tiers: Record<string, SnapshotTierEntry>;
}

export interface RequiredTierResult {
  tierId: string;
  ref: string;
  usableDays: number;
}

function repoRoot(): string {
  // This file lives at <repoRoot>/src/research/snapshot-tier-catalog.ts.
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
}

/**
 * Reads and validates `<root>/snapshot-tiers.json` (default root: this repo's root). Throws with
 * an explicit, actionable message on a missing file, malformed JSON, or an unrecognized
 * `schemaVersion` — fail-closed, never a silent default.
 */
export function loadSnapshotTierCatalog(root: string = repoRoot()): SnapshotTierCatalog {
  const filePath = join(root, 'snapshot-tiers.json');
  let raw: string;
  try {
    raw = readFileSync(filePath, 'utf8');
  } catch (err) {
    throw new Error(
      `snapshot-tier-catalog: cannot read ${filePath} — run control-center's \`pnpm sync\` to (re)generate ` +
      `it and commit the result (${err instanceof Error ? err.message : String(err)})`,
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`snapshot-tier-catalog: ${filePath} is not valid JSON (${err instanceof Error ? err.message : String(err)})`);
  }

  const catalog = parsed as Partial<SnapshotTierCatalog> | null;
  if (!catalog || typeof catalog !== 'object') {
    throw new Error(`snapshot-tier-catalog: ${filePath} does not contain a JSON object`);
  }
  if (catalog.schemaVersion !== SNAPSHOT_TIERS_SCHEMA_VERSION) {
    throw new Error(
      `snapshot-tier-catalog: ${filePath} has unrecognized schemaVersion ${JSON.stringify(catalog.schemaVersion)} ` +
      `— expected ${JSON.stringify(SNAPSHOT_TIERS_SCHEMA_VERSION)}`,
    );
  }
  if (!catalog.tiers || typeof catalog.tiers !== 'object') {
    throw new Error(`snapshot-tier-catalog: ${filePath} is missing a "tiers" object`);
  }

  return catalog as SnapshotTierCatalog;
}

/**
 * The minimal tier whose COMMON grid (the intersection every symbol shares — the only grid valid
 * for a multi-symbol run; see the SSOT comment in the generator) clears `days` of usable history.
 * "Minimal" means the shallowest sufficient tier, not the deepest — a 4-day request should get T1,
 * not be pointed at the much deeper T2. Returns undefined when no committed tier clears `days`.
 */
export function requiredTierForDays(days: number, root?: string): RequiredTierResult | undefined {
  const catalog = loadSnapshotTierCatalog(root);
  const candidates = Object.entries(catalog.tiers)
    .map(([tierId, tier]) => ({ tierId, ref: tier.ref, usableDays: tier.common_present_minutes / MINUTES_PER_DAY }))
    .filter((c) => c.usableDays >= days)
    .sort((a, b) => a.usableDays - b.usableDays);
  return candidates[0];
}
