import { Agent } from '@mastra/core/agent';
import type { ProviderModel } from '../../adapters/llm/model-provider.ts';

export const BUILDER_JUDGE_AGENT_ID = 'builder-judge';

const INSTRUCTIONS = [
  'You are evaluating code generated by a builder agent for a trading overlay module.',
  'You receive: (1) a RUBRIC with scored dimensions, (2) the hypothesis the code should implement,',
  '(3) the module manifest, and (4) the generated TypeScript source.',
  'Score each rubric dimension from 0 to 1 with a short rationale.',
  'List any structural issues or violations (issues).',
  'Be strict and concise. Do not propose fixes; only assess.',
].join(' ');

export function createBuilderJudgeAgent(model: ProviderModel): Agent {
  return new Agent({ id: BUILDER_JUDGE_AGENT_ID, name: 'Builder Judge', instructions: INSTRUCTIONS, model });
}
